import 'package:flutter/material.dart';

extension ColorSchemeExtensions on ColorScheme {
  static ColorScheme fromMap(Map<String, dynamic> map) {
    return ColorScheme(
      brightness: Brightness.values.elementAt(map['brightness']!),
      primary: Color(map["primary"]!),
      onPrimary: Color(map["onPrimary"]!),
      primaryContainer: Color(map["primaryContainer"]!),
      onPrimaryContainer: Color(map["onPrimaryContainer"]!),
      secondary: Color(map["secondary"]!),
      onSecondary: Color(map["onSecondary"]!),
      secondaryContainer: Color(map["secondaryContainer"]!),
      onSecondaryContainer: Color(map["onSecondaryContainer"]!),
      tertiary: Color(map["tertiary"]!),
      onTertiary: Color(map["onTertiary"]!),
      tertiaryContainer: Color(map["tertiaryContainer"]!),
      onTertiaryContainer: Color(map["onTertiaryContainer"]!),
      error: Color(map["error"]!),
      onError: Color(map["onError"]!),
      errorContainer: Color(map["errorContainer"]!),
      onErrorContainer: Color(map["onErrorContainer"]!),
      background: Color(map["background"]!),
      onBackground: Color(map["onBackground"]!),
      surface: Color(map["surface"]!),
      onSurface: Color(map["onSurface"]!),
      surfaceVariant: Color(map["surfaceVariant"]!),
      onSurfaceVariant: Color(map["onSurfaceVariant"]!),
      outline: Color(map["outline"]!),
      outlineVariant: Color(map["outlineVariant"]!),
      shadow: Color(map["shadow"]!),
      scrim: Color(map["scrim"]!),
      inverseSurface: Color(map["inverseSurface"]!),
      onInverseSurface: Color(map["onInverseSurface"]!),
      inversePrimary: Color(map["inversePrimary"]!),
      surfaceTint: Color(map["surfaceTint"]!),
    );
  }

  Map<String, int> get toMap {
    return {
      "brightness": brightness.index,
      "primary": primary.value,
      "onPrimary": onPrimary.value,
      "primaryContainer": primaryContainer.value,
      "onPrimaryContainer": onPrimaryContainer.value,
      "secondary": secondary.value,
      "onSecondary": onSecondary.value,
      "secondaryContainer": secondaryContainer.value,
      "onSecondaryContainer": onSecondaryContainer.value,
      "tertiary": tertiary.value,
      "onTertiary": onTertiary.value,
      "tertiaryContainer": tertiaryContainer.value,
      "onTertiaryContainer": onTertiaryContainer.value,
      "error": error.value,
      "onError": onError.value,
      "errorContainer": errorContainer.value,
      "onErrorContainer": onErrorContainer.value,
      "background": background.value,
      "onBackground": onBackground.value,
      "surface": surface.value,
      "onSurface": onSurface.value,
      "surfaceVariant": surfaceVariant.value,
      "onSurfaceVariant": onSurfaceVariant.value,
      "outline": outline.value,
      "outlineVariant": outlineVariant.value,
      "shadow": shadow.value,
      "scrim": scrim.value,
      "inverseSurface": inverseSurface.value,
      "onInverseSurface": onInverseSurface.value,
      "inversePrimary": inversePrimary.value,
      "surfaceTint": surfaceTint.value,
    };
  }
}
