include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - macros
  errors:
    no_wildcard_variable_uses: ignore
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
