targets:
  $default:
    builders:
      dart_mappable_builder:
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart':
              - 'lib/{{path}}/generated/{{file}}.mapper.dart'
              - 'lib/{{path}}/generated/{{file}}.init.dart'
      source_gen|combining_builder:
        options:
          build_extensions:
            'lib/{{path}}/{{}}.dart':
              - 'lib/{{path}}/generated/{{}}.g.dart'
      content_library|source_generator:
        generate_for:
          - lib/**.dart

builders:
  source_generator:
    import: "package:content_library/src/generators/source_generator.dart"
    builder_factories: ["sourceGenerator"]
    build_extensions:
      "lib/{{path}}/source_enum.dart":
        - "lib/{{path}}/generated/source_enum.dart"
    # auto_apply: all_packages
    build_to: source
    auto_apply: all_packages

    runs_before:
      - isar_generator

    # applies_builders:
    #   - dart_mappable_builder